### ISSUE TITLE
Parameters before *args are not shown in the help message

### ISSUE THREAD

**Issue by ealap** [eonu/feud#113]
### Has this already been reported?

- [X] This is a new bug!

### Expected behaviour

All defined options are still shown with or without any *args.
```python
def serve(port: int = 1, watch: bool = True, env: Literal["dev", "prod"] = "dev"):
```

```
python "main.py" --help
                                                                       
 Usage: main.py [OPTIONS]                                              
                                                                       
 Start a local HTTP server.                                            
                                                                       
╭─ Options ───────────────────────────────────────────────────────────╮
│ --port                INTEGER     Server port. [default: 1]         │
│ --watch/--no-watch                Watch source code for changes.    │
│                                   [default: watch]                  │
│ --env                 [dev|prod]  Environment mode. [default: dev]  │
│ --help                            Show this message and exit.       │
╰─────────────────────────────────────────────────────────────────────╯
```

### Observed behaviour

Defined options are not shown if they are not preceded by *args

```python
def serve(port: int = 1, watch: bool = True, env: Literal["dev", "prod"] = "dev"):
```

```
python "main.py" --help         
                                                                       
 Usage: main.py [OPTIONS] PORT WATCH {dev|prod}                        
                                                                       
 Start a local HTTP server.                                            
                                                                       
╭─ Options ───────────────────────────────────────────────────────────╮
│ --help      Show this message and exit.                             │
╰─────────────────────────────────────────────────────────────────────╯
```

If I add `*` or `*args` somewhere else except the last, then the rest of the commands after it is now shown
```python
def serve(port: int = 1, watch: bool = True, *, env: Literal["dev", "prod"] = "dev"):
```

```
python "main.py" --help
                                                                       
 Usage: main.py [OPTIONS] PORT WATCH                                   
                                                                       
 Start a local HTTP server.                                            
                                                                       
╭─ Options ───────────────────────────────────────────────────────────╮
│ --env     [dev|prod]  Environment mode. [default: dev]              │
│ --help                Show this message and exit.                   │
╰─────────────────────────────────────────────────────────────────────╯
```

### Version details

```Text
Python: 3.12.1
Feud: 0.1.4
Operating system: Debian 12-bookworm
```

**Comment by eonu** [comment]
Hi @ealap, glad to see people already using the package!

So there are two things going on here:

1. When you define the function without the `*` operator anywhere in the signature, it means that those parameters will all be treated as **arguments** (not options).

    ```python
    def serve(port: int = 1, watch: bool = True, env: Literal["dev", "prod"] = "dev"):
    ```

    In regular Python, you could call this function without providing parameter names, because the parameters are positional parameters, e.g. `serve(8080, False, "prod")`.

    Feud kind of interprets it in the same way, and converts those into command-line arguments (rather than options), which are positional only.

    If you want them to be options, you will need the `*` operator in the signature.

2. Related to the first point, since all of the parameters are treated as positional arguments (since you provided no `*`), and since the [default for `rich-click` is to hide arguments in `--help`](https://github.com/ewels/rich-click#positional-arguments), this is why they are not being shown.

    You can fix this by simply changing that setting:

    ```python
    import feud
    from feud import click

    click.rich_click.SHOW_ARGUMENTS = True

    # there are also other settings, e.g.:
    # click.rich_click.MAX_WIDTH = 55

    def serve(port: int = 1, watch: bool = True, *, env: Literal["dev", "prod"] = "dev"):
        ...

    if __name__ == "__main__":
        feud.run(serve)
    ```

    ```
     ▶ python test.py --help
                                                      
     Usage: test.py [OPTIONS] PORT WATCH                  
                                                      
    ╭─ Arguments ────────────────────────────────────────╮
    │ *  PORT     INTEGER  [required]                    │
    │ *  WATCH    BOOLEAN  [required]                    │
    ╰────────────────────────────────────────────────────╯
    ╭─ Options ──────────────────────────────────────────╮
    │ --env     [dev|prod]  [default: dev]               │
    │ --help                Show this message and exit.  │
    ╰────────────────────────────────────────────────────╯
    ```

Thank you for pointing this out, as it seems I forgot to add that `click.rich_click.SHOW_ARGUMENTS = True` to the examples in the `README.md`.

I might also look into changing that to be the default, as it makes more sense than hiding the arguments.

**Comment by eonu** [comment]
Closing this, as the default will now be to show arguments in v0.1.5 (will be released soon).

**Comment by ealap** [comment]
Hi @eonu, thanks for implementing it as default. I was already familiar with `rich-click`'s inline global options, but it didn't crossed my mind to look at it when I encountered this issue.

By the way, I really appreciate you publishing this module! I look forward to using this more going forward.

**Comment by eonu** [comment]
> Hi @eonu, thanks for implementing it as default. I was already familiar with `rich-click`'s inline global options, but it didn't crossed my mind to look at it when I encountered this issue.
> 
> By the way, I really appreciate you publishing this module! I look forward to using this more going forward.

No worries at all 🙂

If you're curious, [this](https://docs.feud.wiki/en/latest/sections/config/index.html#feud.config.Config.rich_click_kwargs) is where you can specify `rich-click` settings.

You can provide your own settings to `@feud.command`, e.g.

```python
import feud

@feud.command(rich_click_kwargs={"max_width": 60})
def func(arg: str):
    ...

if __name__ == "__main__":
    func()
```

Or if you prefer to not decorate the function (e.g. it's a previously defined function used elsewhere), it can be provided as part of the `feud.run` configuration:

```python
import feud

@feud.command(rich_click_kwargs={"max_width": 60})
def func(arg: str):
    ...

if __name__ == "__main__":
    feud.run(
        func,
        config=feud.config(rich_click_kwargs={"max_width": 60}),
    )
```
