### ISSUE TITLE
Seamless integration with existing click CLI

### ISSUE THREAD

**Issue by vikigenius** [eonu/feud#162]
### Does this suggestion already exist?

- [X] This is a new feature!

### Feature description

Take for instance I am using the Litestar framework that already has an extensive CLI implemented on top of click.

I want to extend it by adding additional commands instead of rewriting the entire CLI myself (maybe in the future).

Is there an easy way I can simply do something like

```python
existing_cli.add_command(Blog)  # Blog is a feud.Group
```

**Comment by eonu** [comment]
Hey @vikigenius, thanks for checking out the package.

This should be possible by using [`feud.build`](https://feud.readthedocs.io/en/latest/sections/core/run.html#feud.core.build) to compile the group into a Click object.

```python
import feud

type(existing_cli)
<class 'click.Group'>

class Blog(feud.Group)
    ...

blog = feud.build(Blog)
type(blog)
<class 'click.Group'>

existing_cli.add_command(blog)
```
