### ISSUE TITLE
Include type stubs

### ISSUE THREAD

**Issue by vikigenius** [eonu/feud#164]
### Does this suggestion already exist?

- [X] This is a new feature!

### Feature description

Currently importing feud causes type checkers to complain about missing type stubs.

Please provide type stubs to solve them.

**Comment by eonu** [comment]
Hey @vikigenius thanks for flagging this, will take a look in the next few weeks

**Comment by vikigenius** [comment]
I am using pyright or more specifically the basedpyright fork.

But mypy is also a very popular alternative

**Comment by eonu** [comment]
Hey @vikigenius, I've added initial type stubs in #171, which will be going into the latest release.

I've also added static type checking with mypy as part of the development workflow.

Curious to know if it works with basedpyright, please let me know! Will reopen this if you come across any other issues.
